namespace TestsGenerator.Tests;

using TestsGenerator.Core;

public class TestsGeneratorTests
{
    private static string LoadTestClassSource(string fileName) =>
        File.ReadAllText(Path.Join(AppContext.BaseDirectory, "TestClasses", fileName));

    [Fact]
    public void TestSinglePublicClass()
    {
        var source = LoadTestClassSource("SinglePublicClass.cs");
        var results = TestsGenerator.GenerateTests(source);

        Assert.Single(results);
        var output = results[0];
        Assert.Equal("Calculator", output.ClassName);

        var root = TestUtils.ParseRoot(output.Source);
        var testClass = TestUtils.GetSingleClass(root);

        Assert.Equal("CalculatorTests", testClass.Identifier.Text);
        Assert.True(TestUtils.HasUsing(root, "Xunit"));
        Assert.True(TestUtils.HasUsing(root, "TestsGenerator.Tests.TestData"));
        Assert.True(TestUtils.HasPrivateField(testClass, "_calculator"));
        Assert.True(TestUtils.ContainsAutogeneratedFailMessage(root));

        var factMethods = TestUtils.MethodsWithFact(testClass);
        var names = factMethods.Select(m => m.Identifier.Text).OrderBy(n => n).ToArray();
        Assert.Equal(new[] { "AddTest", "ResetTest" }, names);
    }

    [Fact]
    public void TestTwoPublicClassesInOneFile()
    {
        var source = LoadTestClassSource("TwoPublicClasses.cs");
        var results = TestsGenerator.GenerateTests(source);

        Assert.Equal(2, results.Count);
        var names = results.Select(r => r.ClassName).OrderBy(n => n).ToArray();
        Assert.Equal(new[] { "Alpha", "Beta" }, names);

        foreach (var r in results)
        {
            var root = TestUtils.ParseRoot(r.Source);
            var testClass = TestUtils.GetSingleClass(root);
            Assert.NotEmpty(TestUtils.MethodsWithFact(testClass));
        }
    }

    [Fact]
    public void TestOnlyInternalClass()
    {
        var source = LoadTestClassSource("InternalOnly.cs");
        var results = TestsGenerator.GenerateTests(source);

        Assert.Empty(results);
    }

    [Fact]
    public void TestOverloadedMethods()
    {
        var source = LoadTestClassSource("MethodOverloads.cs");
        var results = TestsGenerator.GenerateTests(source);

        Assert.Single(results);
        Assert.Equal("OverloadedMethods", results[0].ClassName);

        var root = TestUtils.ParseRoot(results[0].Source);
        var testClass = TestUtils.GetSingleClass(root);
        var factNames = TestUtils.MethodsWithFact(testClass)
            .Select(m => m.Identifier.Text)
            .OrderBy(n => n)
            .ToArray();

        Assert.Equal(new[] { "Execute1Test", "Execute2Test" }, factNames);
    }

    [Fact]
    public void TestConstructorWithInterface()
    {
        var source = LoadTestClassSource("ClassWithInterfaceDependency.cs");
        var results = TestsGenerator.GenerateTests(source);

        var dataService = Assert.Single(results, r => r.ClassName == "ClassWithDependency");

        var root = TestUtils.ParseRoot(dataService.Source);
        var testClass = TestUtils.GetSingleClass(root);

        Assert.True(TestUtils.HasUsing(root, "Moq"));
        Assert.True(TestUtils.HasUsing(root, "TestsGenerator.Tests.TestData"));
        Assert.True(TestUtils.HasMockFieldForInterface(testClass, "IDependency", "_depMock"));
        Assert.True(TestUtils.HasPrivateField(testClass, "_classWithDependency"));

        var factNames = TestUtils.MethodsWithFact(testClass)
            .Select(m => m.Identifier.Text)
            .ToArray();
        Assert.Contains("PublishTest", factNames);
    }

    [Fact]
    public void TestFileScopedNamespace()
    {
        var source = LoadTestClassSource("FileScopedNamespace.cs");
        var results = TestsGenerator.GenerateTests(source);

        Assert.Single(results);
        Assert.Equal("FileScopedNamespace", results[0].ClassName);

        var root = TestUtils.ParseRoot(results[0].Source);
        var ns = TestUtils.GetSingleNamespace(root);

        Assert.Equal("TestsGenerator.Tests.TestData.FileScoped.Tests", ns.Name.ToString());

        var testClass = TestUtils.GetSingleClass(root);
        var factNames = TestUtils.MethodsWithFact(testClass)
            .Select(m => m.Identifier.Text)
            .ToArray();
        Assert.Contains("MethodTest", factNames);
    }
}
