namespace TestsGenerator.Tests;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal static class TestUtils
{
    public static CompilationUnitSyntax ParseRoot(string generatedSource)
    {
        var tree = CSharpSyntaxTree.ParseText(generatedSource);
        return tree.GetCompilationUnitRoot();
    }

    public static NamespaceDeclarationSyntax GetSingleNamespace(CompilationUnitSyntax root) =>
        Assert.Single(root.Members.OfType<NamespaceDeclarationSyntax>());

    public static ClassDeclarationSyntax GetSingleClass(CompilationUnitSyntax root)
    {
        var ns = GetSingleNamespace(root);
        return Assert.Single(ns.Members.OfType<ClassDeclarationSyntax>());
    }

    public static bool HasUsing(CompilationUnitSyntax root, string namespaceOrTypeName) =>
        root.Usings.Any(u => u.Name?.ToString() == namespaceOrTypeName);

    public static IReadOnlyList<MethodDeclarationSyntax> MethodsWithFact(ClassDeclarationSyntax type) =>
        type.Members
            .OfType<MethodDeclarationSyntax>()
            .Where(m => m.AttributeLists
                .SelectMany(a => a.Attributes)
                .Any(a => a.Name is IdentifierNameSyntax id && id.Identifier.Text == "Fact"))
            .ToList();

    public static bool HasPrivateField(ClassDeclarationSyntax type, string fieldName) =>
        type.Members
            .OfType<FieldDeclarationSyntax>()
            .Where(f => f.Modifiers.Any(m => m.IsKind(SyntaxKind.PrivateKeyword)))
            .SelectMany(f => f.Declaration.Variables)
            .Any(v => v.Identifier.Text == fieldName);

    public static bool HasMockFieldForInterface(ClassDeclarationSyntax type, string interfaceName, string fieldName)
    {
        foreach (var field in type.Members.OfType<FieldDeclarationSyntax>())
        {
            foreach (var variable in field.Declaration.Variables)
            {
                if (variable.Identifier.Text != fieldName)
                    continue;

                if (field.Declaration.Type is not GenericNameSyntax generic)
                    continue;

                if (generic.Identifier.Text != "Mock")
                    continue;

                var args = generic.TypeArgumentList.Arguments;
                if (args.Count != 1)
                    continue;

                if (args[0].ToString() == interfaceName)
                    return true;
            }
        }

        return false;
    }

    public static bool ContainsAutogeneratedFailMessage(CompilationUnitSyntax root) =>
        root.DescendantNodes()
            .OfType<LiteralExpressionSyntax>()
            .Any(l =>
                l.IsKind(SyntaxKind.StringLiteralExpression) &&
                l.Token.ValueText == "autogenerated");
}
