namespace TestsGenerator.Core;

using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

public static class TestsGenerator
{
    public static List<GeneratorOutput> GenerateTests(string source)
    {
        var results = new List<GeneratorOutput>();

        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var root = syntaxTree.GetCompilationUnitRoot();

        var originalUsings = root.Usings;
        var classDeclarations = root.DescendantNodes().OfType<ClassDeclarationSyntax>();

        foreach (var classDecl in classDeclarations)
        {
            if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)))
                continue;

            var className = classDecl.Identifier.Text;

            string? namespaceName = null;
            SyntaxNode? nsNode = classDecl.Parent;
            while (nsNode != null)
            {
                if (nsNode is NamespaceDeclarationSyntax nsDecl)
                {
                    namespaceName = nsDecl.Name.ToString();
                    break;
                }

                if (nsNode is FileScopedNamespaceDeclarationSyntax fsNsDecl)
                {
                    namespaceName = fsNsDecl.Name.ToString();
                    break;
                }
                
                nsNode = nsNode.Parent;
            }

            var publicMethods = classDecl.Members
                .OfType<MethodDeclarationSyntax>()
                .Where(m => m.Modifiers.Any(mod => mod.IsKind(SyntaxKind.PublicKeyword)))
                .ToList();

            var methodGroups = publicMethods
                .GroupBy(m => m.Identifier.Text)
                .ToList();

            var testMethods = new List<MemberDeclarationSyntax>();

            foreach (var group in methodGroups)
            {
                var methods = group.ToList();
                bool hasOverloads = methods.Count > 1;

                for (int i = 0; i < methods.Count; i++)
                {
                    string testMethodName = hasOverloads
                        ? $"{group.Key}{i + 1}Test"
                        : $"{group.Key}Test";

                    var factAttribute = AttributeList(
                        SingletonSeparatedList(
                            Attribute(IdentifierName("Fact"))
                        )
                    );

                    var assertStatement = ExpressionStatement(
                        InvocationExpression(
                            MemberAccessExpression(
                                SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("Assert"),
                                IdentifierName("True")
                            ),
                            ArgumentList(
                                SeparatedList<ArgumentSyntax>(new[]
                                {
                                    Argument(
                                        LiteralExpression(SyntaxKind.FalseLiteralExpression)
                                    ),
                                    Argument(
                                        LiteralExpression(
                                            SyntaxKind.StringLiteralExpression,
                                            Literal("autogenerated")
                                        )
                                    )
                                })
                            )
                        )
                    );

                    var testMethod = MethodDeclaration(
                            PredefinedType(Token(SyntaxKind.VoidKeyword)),
                            Identifier(testMethodName)
                        )
                        .AddModifiers(Token(SyntaxKind.PublicKeyword))
                        .AddAttributeLists(factAttribute)
                        .WithBody(Block(assertStatement));

                    testMethods.Add(testMethod);
                }
            }

            string testClassName = $"{className}Tests";

            var testClass = ClassDeclaration(testClassName)
                .AddModifiers(Token(SyntaxKind.PublicKeyword))
                .AddMembers(testMethods.ToArray());

            var usings = new List<UsingDirectiveSyntax>();

            foreach (var u in originalUsings)
                usings.Add(u.WithoutTrivia());

            if (!usings.Any(u => u.Name?.ToString() == "Xunit"))
                usings.Add(UsingDirective(IdentifierName("Xunit")));

            if (namespaceName != null &&
                !usings.Any(u => u.Name?.ToString() == namespaceName))
            {
                usings.Add(UsingDirective(ParseName(namespaceName)));
            }

            string testNamespace = namespaceName != null
                ? $"{namespaceName}.Tests"
                : "Tests";

            var namespaceMember = NamespaceDeclaration(ParseName(testNamespace))
                .AddMembers(testClass);

            var compilationUnit = CompilationUnit()
                .AddUsings(usings.ToArray())
                .AddMembers(namespaceMember)
                .NormalizeWhitespace();

            results.Add(new GeneratorOutput(className, compilationUnit.ToFullString()));
        }

        return results;
    }
}
